name: <clientcode>-analytics
env_file:
  - .env
services:
  appserver:
    type: python:3.7
    portforward: true
    build:
      # Install dbt
      - pip install -r requirements.txt
      # Install dependencies
      - cd /app && dbt deps
      # Install dbt bash completion
      - curl https://raw.githubusercontent.com/fishtown-analytics/dbt-completion.bash/master/dbt-completion.bash > ~/.dbt-completion.bash
      - echo 'source ~/.dbt-completion.bash' >> ~/.bash_profile
      - source ~/.bash_profile
    run_as_root:
      - "apt-get update -y"
      - "apt-get install vim -y"
      - "apt-get install git libpq-dev python-dev python3-pip -y"
  # We really only need one database on our local to perform development work against
  database:
    type: postgres:10
    portforward: true
    creds:
      database: dw
      # Note that you cannot change the below but they are shown here for transparency
      # You can read more about why this is below
      # By "NO PASSWORD" we mean the password is blank
      # user: postgres
      # password: NO PASSWORD
tooling:
  dbt-deps:
    service: appserver
    cmd: cd /app && dbt deps
  dbt-run:
    service: appserver
    cmd: cd /app && dbt run